In [20]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import warnings
from sklearn import datasets, linear_model

import sklearn
from sklearn.linear_model import LogisticRegressionCV,LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model.coordinate_descent import ConvergenceWarning
import matplotlib as mpl

In [21]:
data = pd.read_csv('iBeacon_RSSI_Labeled.csv')

In [22]:
data = data.drop('date', 1)
#data.head()

location  b3001  b3002  b3003  b3004  b3005  b3006  b3007  b3008  b3009  \
0      O02   -200   -200   -200   -200   -200    -78   -200   -200   -200   
1      P01   -200   -200   -200   -200   -200    -78   -200   -200   -200   
2      P01   -200   -200   -200   -200   -200    -77   -200   -200   -200   
3      P01   -200   -200   -200   -200   -200    -77   -200   -200   -200   
4      P01   -200   -200   -200   -200   -200    -77   -200   -200   -200   

   b3010  b3011  b3012  b3013  
0   -200   -200   -200   -200  
1   -200   -200   -200   -200  
2   -200   -200   -200   -200  
3   -200   -200   -200   -200  
4   -200   -200   -200   -200

In [23]:
X = data[['b3001','b3002','b3003','b3004','b3005','b3006','b3007','b3008','b3009','b3010','b3011','b3012','b3013']]
X.shape

(1420, 13)

In [24]:
y = data[['location']]
#y.head()
#y_train.shape

location
0      O02
1      P01
2      P01
3      P01
4      P01

In [25]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [26]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1065, 13)
(1065, 1)
(355, 13)
(355, 1)


In [27]:
#X_train.head()

b3001  b3002  b3003  b3004  b3005  b3006  b3007  b3008  b3009  b3010  \
602    -200   -200   -200   -200   -200   -200   -200   -200    -78    -72   
1165   -200   -200    -77   -200   -200   -200   -200   -200   -200   -200   
62     -200    -77   -200   -200   -200   -200   -200   -200   -200   -200   
1199   -200   -200   -200    -78   -200   -200   -200   -200   -200   -200   
315    -200   -200   -200   -200   -200    -67   -200   -200   -200   -200   

      b3011  b3012  b3013  
602    -200   -200   -200  
1165   -200   -200   -200  
62     -200   -200   -200  
1199   -200   -200   -200  
315    -200   -200   -200

In [28]:
#1、svm
from sklearn import svm
clf = svm.SVC(gamma=0.001)
clf.fit(X_train, y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [29]:
clf.predict(X_test)

array(['J04', 'S01', 'L06', 'J07', 'I01', 'D15', 'M06', 'F08', 'S05',
       'S01', 'N06', 'J04', 'J04', 'N06', 'W15', 'N06', 'R04', 'R04',
       'S01', 'K04', 'J04', 'N05', 'S01', 'S01', 'O05', 'S01', 'J04',
       'K04', 'N03', 'O06', 'P15', 'J04', 'I01', 'S05', 'J04', 'W15',
       'O05', 'I01', 'S01', 'D13', 'M01', 'J04', 'J04', 'J04', 'D13',
       'S01', 'K04', 'N06', 'I01', 'L06', 'O06', 'J07', 'J04', 'N05',
       'I01', 'I01', 'N03', 'M03', 'I06', 'S05', 'M01', 'D13', 'S05',
       'N05', 'S05', 'J04', 'R04', 'N03', 'J04', 'S01', 'J04', 'R15',
       'J06', 'I07', 'J04', 'W15', 'M01', 'K04', 'L06', 'S01', 'S01',
       'I08', 'L06', 'D15', 'S01', 'O06', 'I10', 'R04', 'O06', 'N03',
       'K04', 'I01', 'S06', 'O05', 'M01', 'O06', 'J06', 'I08', 'N05',
       'P15', 'K04', 'S01', 'J04', 'M06', 'M03', 'I08', 'K07', 'S01',
       'S01', 'S01', 'J05', 'K05', 'S05', 'J04', 'L06', 'J06', 'S01',
       'S01', 'J04', 'M01', 'I10', 'S01', 'S01', 'S06', 'L15', 'N06',
       'L15', 'S01',

In [30]:
clf.score(X_test, y_test)

0.2028169014084507

In [31]:
clf.score(X_train, y_train)

0.29107981220657275

In [11]:
#2、决策树
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.predict(X_test)

array(['J02', 'S01', 'J07', 'J07', 'J02', 'D15', 'J08', 'I04', 'Q05',
       'U04', 'O06', 'I04', 'J03', 'N01', 'V15', 'M06', 'S03', 'Q04',
       'S01', 'K04', 'I04', 'M02', 'O05', 'Q05', 'O05', 'O05', 'J03',
       'J02', 'M01', 'L02', 'P15', 'J02', 'I01', 'R05', 'I02', 'W15',
       'P05', 'K03', 'O05', 'D13', 'L04', 'I04', 'J01', 'I01', 'D13',
       'S01', 'K04', 'M06', 'J02', 'J07', 'L02', 'L05', 'I02', 'N05',
       'J01', 'I05', 'N02', 'N03', 'I06', 'S05', 'L04', 'D13', 'S05',
       'N05', 'S05', 'I02', 'Q01', 'N02', 'J03', 'U04', 'J03', 'R15',
       'J06', 'I10', 'K04', 'S15', 'K03', 'J02', 'J08', 'S01', 'R03',
       'I08', 'I03', 'D15', 'S01', 'L02', 'I08', 'S03', 'K06', 'L01',
       'J02', 'I01', 'S08', 'P05', 'M01', 'K06', 'M05', 'J02', 'L05',
       'P15', 'K04', 'P03', 'I04', 'K08', 'N03', 'I09', 'I10', 'O05',
       'P03', 'P03', 'J05', 'L04', 'S05', 'K04', 'L06', 'J06', 'S01',
       'P03', 'K04', 'L01', 'I10', 'R03', 'T05', 'R03', 'L15', 'N06',
       'L15', 'R03',

In [ ]:
clf.score()

In [ ]:
clf.score(X_test, y_test)

In [ ]:
clf.score(X_train, y_train)

In [36]:
from sklearn import preprocessing  
le =preprocessing.LabelEncoder()  
le.fit(y_train)  
#print('标签个数:%s'% le.classes_)  
y_train=le.transform(y_train)
#print('标准化标签值反转:%s' % le.inverse_transform([2, 2, 1]))  

#标签个数:['amsterdam' 'paris' 'tokyo']  
#标签值标准化:[2 2 1]  
#标准化标签值反转:['tokyo' 'tokyo' 'paris']
y_train

array([16, 73, 37, ..., 20, 54, 39])

In [46]:
#3、随机森林
from sklearn import tree
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)
clf.predict(X_test)

array([ 18.7       ,  84.6875    ,  24.2       ,  23.        ,
        16.85714286,   2.        ,  32.        ,   4.        ,
        82.18181818,  86.9       ,  53.4       ,  14.16666667,
        16.83333333,  56.        , 103.        ,  55.33333333,
        85.        ,  73.        ,  84.6875    ,  18.44444444,
        14.16666667,  54.75      ,  78.625     ,  84.72727273,
        61.        ,  86.29411765,  18.44444444,   8.        ,
        35.        ,  56.14285714,  43.        ,  18.7       ,
        20.        ,  80.        ,  21.3       , 104.        ,
        67.        ,  23.55555556,  86.29411765,   0.        ,
        51.        ,  14.16666667,  22.        ,  20.9       ,
         0.        ,  81.86363636,  30.        ,  55.33333333,
        16.85714286,  24.2       ,  56.14285714,  39.        ,
        24.83333333,  46.9       ,  33.16666667,  24.        ,
        51.        ,  46.        ,  11.        ,  87.4       ,
        51.        ,   0.        ,  87.4       ,  46.9 

In [45]:
X_test=le.transform(X_test)
clf.score(X_test, y_test)

ValueError: bad input shape (355, 13)

In [39]:
y_test

location
169       M04
37        S02
512       I07
912       J07
341       K06
383       D15
435       J07
1086      I04
1023      Q05
1040      O05
223       L05
48        J03
194       J04
236       N05
863       W15
311       O06
80        O03
1163      Q04
259       Q05
830       I02
1117      L04
487       M02
101       R03
685       S08
1047      O05
1227      Q03
432       J06
572       K04
481       M01
301       Q06
...       ...
767       J04
709       L02
1078      J05
921       I04
303       P06
1233      P03
216       K05
819       I04
1318      S01
631       V15
202       I04
916       J02
989       S06
310       O06
1268      K03
653       S04
8         R01
241       O05
368       J07
494       N01
757       J02
735       K04
1062      L05
1059      M05
821       I03
275       R05
1083      I05
643       S02
994       S06
804       I08

[355 rows x 1 columns]

In [19]:
Y_test

array([ 18.7       ,  84.6875    ,  24.2       ,  23.        ,
        16.85714286,   2.        ,  32.        ,   4.        ,
        82.18181818,  86.9       ,  53.4       ,  14.16666667,
        16.83333333,  56.        , 103.        ,  55.33333333,
        85.        ,  73.        ,  84.6875    ,  18.44444444,
        14.16666667,  54.75      ,  78.625     ,  84.72727273,
        61.        ,  86.29411765,  18.44444444,   8.        ,
        35.        ,  56.14285714,  43.        ,  18.7       ,
        20.        ,  80.        ,  21.3       , 104.        ,
        67.        ,  23.55555556,  86.29411765,   0.        ,
        51.        ,  14.16666667,  22.        ,  20.9       ,
         0.        ,  81.86363636,  30.        ,  55.33333333,
        16.85714286,  24.2       ,  56.14285714,  39.        ,
        24.83333333,  46.9       ,  33.16666667,  24.        ,
        51.        ,  46.        ,  11.        ,  87.4       ,
        51.        ,   0.        ,  87.4       ,  46.9 